USE [master]
GO

/****** Object:  Database [NPOSPARCK]    Script Date: 19.12.2022 19:09:37 ******/
DROP DATABASE [NPOSPARCK]
GO

/****** Object:  Database [NPOSPARCK]    Script Date: 19.12.2022 19:09:37 ******/
CREATE DATABASE [NPOSPARCK]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CInfo2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\CInfo2.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CInfo2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\CInfo2_log.ldf' , SIZE = 1040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [NPOSPARCK] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NPOSPARCK].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NPOSPARCK] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NPOSPARCK] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NPOSPARCK] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NPOSPARCK] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NPOSPARCK] SET ARITHABORT OFF 
GO

ALTER DATABASE [NPOSPARCK] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [NPOSPARCK] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [NPOSPARCK] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NPOSPARCK] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NPOSPARCK] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NPOSPARCK] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NPOSPARCK] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NPOSPARCK] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NPOSPARCK] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NPOSPARCK] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NPOSPARCK] SET  ENABLE_BROKER 
GO

ALTER DATABASE [NPOSPARCK] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NPOSPARCK] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NPOSPARCK] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NPOSPARCK] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NPOSPARCK] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NPOSPARCK] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [NPOSPARCK] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NPOSPARCK] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NPOSPARCK] SET  MULTI_USER 
GO

ALTER DATABASE [NPOSPARCK] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NPOSPARCK] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NPOSPARCK] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NPOSPARCK] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [NPOSPARCK] SET  READ_WRITE 
GO


